require_relative 'extensions/torrent_actions'
require_relative 'extensions/torrent_attributes'
require_relative 'extensions/torrent_prettify'
require_relative 'extensions/torrent_status'
require_relative 'extensions/transmission_selectors'
